name: create release from upstream latest relase tag

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: macos-10.15

    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: update fork
        run: |
          bash <(curl --silent https://raw.githubusercontent.com/billypchan/iosGitHubTools/master/scripts/updateFork.sh) https://github.com/apple/swift-protobuf

      - name: check out release tag
        run: |
          bash <(curl --silent https://raw.githubusercontent.com/billypchan/iosGitHubTools/master/scripts/checkoutReleaseTag.sh) apple/swift-protobuf

      - name: make framwwork
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
        run: |
          ls -n /Applications/ | grep Xcode*
          bash <(curl --silent https://raw.githubusercontent.com/billypchan/iosGitHubTools/master/scripts/createCarthageFramwork.sh)

      - name: submit release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash <(curl --silent https://raw.githubusercontent.com/billypchan/iosGitHubTools/master/scripts/submitCarthageRelease.sh) apple/swift-protobuf
        
